<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <UserSecretsId>hangfire-worker-secrets</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.17" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.9.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pragmatic.TemplateApi.Core\Pragmatic.TemplateApi.Core.csproj" />
    <ProjectReference Include="..\Pragmatic.TemplateApi.Instrumentation\Pragmatic.TemplateApi.Instrumentation.csproj" />
    <ProjectReference Include="..\Pragmatic.TemplateApi.Database\Pragmatic.TemplateApi.Database.csproj" />
  </ItemGroup>

</Project>
