services:

  template.testedapi.api:
    image: ghcr.io/tristanrhodes/template.testedapi.api:latest
    container_name: template.testedapi.api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__PostgresDb=Host=local-postgres;Port=5432;Username=postgres;Password=password;Database=shop;
      - OpenIdConnect__Issuer=https://localhost:8443/realms/todolist-realm
      - OpenIdConnect__Audience=todolist-client
      - OpenIdConnect__OpenIdConfigUrl=https://localhost:8443/realms/todolist-realm/.well-known/openid-configuration
    networks:
      - local

  template.testedapi.database:
    image: ghcr.io/tristanrhodes/template.testedapi.database:latest
    container_name: template.testedapi.database
    environment:
      - DbConnectionString=Host=local-postgres;Port=5432;Username=postgres;Password=password;Database=shop;
    networks:
      - local

networks:
  local:
