<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UserSecretsId>906f752f-f3ab-4819-8b5c-43d9bd0ab85c</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Uris" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.17" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.8.17" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pragsys.TemplateApi.Core\Pragsys.TemplateApi.Core.csproj" />
    <ProjectReference Include="..\Pragsys.TemplateApi.Database\Pragsys.TemplateApi.Database.csproj" />
    <ProjectReference Include="..\Pragsys.TemplateApi.Instrumentation\Pragsys.TemplateApi.Instrumentation.csproj" />
  </ItemGroup>

</Project>
