
name: Build and Test Solution
run-name: Build and Test Solution

on:
  pull_request:
    branches:    
      - main

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # This is necessary so it does not conflict with git-version

      - name: Run cake step
        uses: cake-build/cake-action@v3
        with:
          script-path: build.cake
          target: BuildAndTest

      - name: Publish Test Report with Pull Request Comment
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './artifacts/*.trx'
          pull-request-report: true
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Test Results
        uses: dorny/test-reporter@v3
        with:
          name: Test Results
          path: artifacts/*.trx
          reporter: dotnet-trx
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: ./artifacts/